### ISSUE TITLE
Plattar Exporter doesn't appear in Unity menu

### ISSUE THREAD

**Issue by VoxelOne** [Plattar/gltf-exporter#1]
Using Unity v2019.1.5.f1. After importing the package, I get the attached warning in the console and the Plattar Exporter menu option doesn't show up. Using Win10 build 1803 (17134.829)

Sadly I'm very much a novice, so I'm not sure how to fix the script.

![image](https://user-images.githubusercontent.com/52089624/59956739-e9a46f00-9446-11e9-9ace-086056f3ef9b.png)

Thanks in advance!

**Comment by DavidArayan** [comment]
Thank you for the report @VoxelOne, I've replicated the issue and will be fixed in the next release. It seems to occur when you switch out of the "Windows" build mode into another platform. Thank you for the report!

**Comment by DavidArayan** [comment]
Hello @VoxelOne, we have fixed the issue with the latest [Release 1.62.0](https://github.com/Plattar/gltf-exporter/releases/tag/1.62.0). Let me know if there are any further issues. 

Cheers!

**Comment by VoxelOne** [comment]
That’s awesome! Can’t wait to check it out later today! Thank you so much for being so responsive. 

So glad gltf is gaining traction, and If this works the way I hope it will, it will really help refine my VR workflow.

**Comment by VoxelOne** [comment]
Hey David, so that worked perfectly. I exported a model from Unity and it came out perfectly. I did have one last quick question for you, however. The model I exported had both animated geometry AND an animated texture. The animated geometry passed through perfectly, but the animated texture did not. Does gltf support animated textures?

**Comment by DavidArayan** [comment]
Hello VoxelOne, could you explain how the texture is animated? Texture animation is not supported in the GLTF core spec and so any programs you use to import them may not support the feature (as such our exporter does not support it). Could I ask where are you importing the GLTF models into?

**Comment by VoxelOne** [comment]
Hello. The texture is on a model borrowed from a tutorial for testing. It is a conveyor belt where the “belt” is simply a bitmap applied to a plane and the uv is animated in one direction. 

The program we are importing these into is Presentation Designer — a product made by WorldViz. It has recently begun supporting gltf (.glb, actually). I take the exported gltf from your plugin and open it in Microsoft’s 3D Builder (which seems to preserve it well) and then convert to .glb for WorldViz. Unfortunately, WorldViz doesn’t even import the geometry animation that I can see in 3D Builder.

As a result, I’m thinking I might look into multi-user experience in unity. Our company works with sensitive stuff sometimes, so we can’t really use online multi-user networking services. That could be a challenge.

**Comment by DavidArayan** [comment]
Can't speak about the features of other platforms. GLTF format contains a meta-data section which is essentially a place where extension/misc data can be encoded for specific platforms. 

The way we worked around the animated texture for GLTF in PLATTAR was to simply use a video in place of the texture. Our platform recognises the video file and essentially plays back when the content is presented to the user. This is obviously a specific feature of our platform and not part of the GLTF spec.
