### ISSUE TITLE
v1.93.0 package importing console errors

### ISSUE THREAD

**Issue by z3Nsk1Fh5a** [Plattar/gltf-exporter#11]
![01:56:51] Assembly for Assembly Definition File 'Assets/PlattarExporter/Resources/ResourceCompile.asmder will not be compiled, because it has no scripts associated with it. 
! UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:CompileScripts (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,stringfl) 
!(01:56:53] Assets\PlattarExporter1UnityGLTF Scripts1GLIFScenelmporter.cs(103,18): warning CS0618: 'UnityWebRequest.Sencl(l is obsolete: 'Use SendWebRequest. It returns a UnityWebRequestAsyncOperation which contains a reference to the WebRequest object.' 
!(01:56:53] Assets\ PlattarExporter\UnityGLTF Scripts\ GLTFEditorExporter.cs(242,22): warning CS0168: The variable 'e' is declared but never used 
!(01:56:53] Assets1PlattarExporter1UnityGLTF1Scripts1AssetSerializer.cs(306,10): warning CS0618: 'PrefabUtility.CreatePrefab(string, GameObject)' is obsolete: 'Use SaveAsPrefabAsset instead.' 
!(01:56:53] Assets\ PlattarExporter\UnityGLTRScripts GLIFScenelmporter.cs(709,20): warning CS0618: 'UnityWebRequest.Sena is obsolete: 'Use SendWebRequest. It returns a UnityWebRequestAsyncOperation which contains a reference to the WebRequest object.' 
!(01:56:53] Assets‘PlattarExporter1UnityGLTF1Scripts1GLIFScenelmporter.cs(777,19): warning CS0618: 'UnityWebRequest.Send(). is obsolete: 'Use SendWebRequest. It returns a UnityWebRequestAsyncOperation which contains a reference to the WebRequest object.'

**Comment by DavidArayan** [comment]
this should be fixed in latest release [1.142.0](https://github.com/Plattar/gltf-exporter/releases/tag/1.142.0)
