### ISSUE TITLE
Does it support runtime export?

### ISSUE THREAD

**Issue by marcusx2** [Plattar/gltf-exporter#12]
Can I export to gltf a gameobject that is created at runtime? Can I have a reference to said model in memory, and not have to save it?

**Comment by calrk** [comment]
**Can I export to gltf a gameobject that is created at runtime?**
Not by default, but its likely you could modify the library to support this feature.

**Can I have a reference to said model in memory, and not have to save it?**
Again not by default, but it should be possible to do by modifying the save function. What is your use case for this feature?

You can take a look at how the button to create the gltf file works [here](https://github.com/Plattar/gltf-exporter/blob/master/unity-gltf-exporter/Assets/PlattarExporter/Plattar/Editor/Exporter.cs#L227), and use that as a guide to create the features you want.

**Comment by marcusx2** [comment]
> Not by default, but its likely you could modify the library to support this feature.

Can you or do you intend to support this in the future?

> Again not by default, but it should be possible to do by modifying the save function.

Can you or do you intend to support this in the future?

> What is your use case for this feature?

The use case is that a client wants to generate gltf models at runtime an export them to an external webserver to later be used. So I really needed to be able to export a gameobject to gltf at runtime and send it to a webserver using REST or something, so I don't need it to be saved locally at all.

If you can give me some pointers on how to modify the library to accomplish these things before they are implemented(if these additions will ever be implemented), I'd greatly appreciate it. Thank you for your time.

**Comment by cpetry** [comment]
+1

Need this feature and can contribute

**Comment by marcusx2** [comment]
This might help you guys [https://github.com/vrm-c/UniVRM](https://github.com/vrm-c/UniVRM). It has runtime export.
