### ISSUE TITLE
Custom Unity Materials have issues for export

### ISSUE THREAD

**Issue by vulture-boy** [Plattar/gltf-exporter#15]
Hello! This might be a bit of a longshot, but I've noticed that exporting some varieties of custom materials results in material data being lost. For example, exporting an object that looks like this

![image](https://user-images.githubusercontent.com/19735946/150703844-7e44a13c-7992-48a1-8636-cd6525e71a9d.png)

results in 

![image](https://user-images.githubusercontent.com/19735946/150703867-8f05c696-aa9c-4da0-a7be-c51b1ca7eda8.png)

I imagine there are limitations to what can be supported by the exporter tool, but I imagine that custom material types such as these are relatively common in Unity projects and that custom materials need to be in some sort of unified format for Unity to recognize and use them.... hoping that there's an implementable solution for this asset that could be applied in the future.

I should mention that regular material assets export just fine.

**Comment by DavidArayan** [comment]
Hello,

This exporter was not designed to export custom materials/shaders. It only works with built-in materials and PBR materials.
