### ISSUE TITLE
Where is the Toolbar?

### ISSUE THREAD

**Issue by echan00** [Plattar/gltf-exporter#16]
Trying to figure out what I am doing wrong.. I imported PlattarExporter by double clicking on the unity package downloaded from releases section. I see PlattarExporter in the Assets folder now. But no toolbar as suggest in the screenshot.

I am using Unity 2020.3.27f1 Personal 

Am I importing the package incorrectly?

**Comment by DavidArayan** [comment]
this should be fixed in latest release [1.142.0](https://github.com/Plattar/gltf-exporter/releases/tag/1.142.0)
