### ISSUE TITLE
Sound Exporter Support

### ISSUE THREAD

**Issue by ghost** [Plattar/gltf-exporter#2]
Hi,
Thank you for this fantastic exporter for Unity
I would know if is possible to export also "Audio Sorce" and not only Animations
If not, is it in develop?
Thanks again :)

**Comment by DavidArayan** [comment]
Hello flogli,

Happy to know that you're finding the exporter useful, thank you for your feedback!
Unfortunately audio/video sources are not part of the primary GLTF spec so it's unlikely that we will add support. GLTF is a specification that handles 3D model data and we'd like to keep it as close to the specification as possible. What you're looking for it probably a Scene creator that can handle both 3D and Audio data like the one we have at [Plattar](https://www.plattar.com).

Hope that helps!
