### ISSUE TITLE
Error exporting Gameobject

### ISSUE THREAD

**Issue by BaltaKid** [Plattar/gltf-exporter#5]
I don't know if im doing something bad or if is the plugin but when i try do export the GLTF this error appears. i'm trying to export in runtime.

`Exception: Accessors can not have a count of 0.
UnityGLTF.GLTFSceneExporter.ExportAccessor (UnityEngine.Vector3[] arr) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:938)
UnityGLTF.GLTFSceneExporter.ExportPrimitive (UnityEngine.GameObject gameObject) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:304)
UnityGLTF.GLTFSceneExporter.ExportMesh (System.String name, UnityEngine.GameObject[] primitives) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:263)
UnityGLTF.GLTFSceneExporter.ExportNode (UnityEngine.Transform nodeTransform) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:158)
UnityGLTF.GLTFSceneExporter.ExportNode (UnityEngine.Transform nodeTransform) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:175)
UnityGLTF.GLTFSceneExporter.ExportNode (UnityEngine.Transform nodeTransform) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:175)
UnityGLTF.GLTFSceneExporter.ExportNode (UnityEngine.Transform nodeTransform) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:175)
UnityGLTF.GLTFSceneExporter.ExportScene (System.String name, UnityEngine.Transform[] rootObjTransforms) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:125)
UnityGLTF.GLTFSceneExporter.SaveGLTFandBin (System.String path, System.String fileName) (at Assets/PlattarExporter/UnityGLTF/Scripts/GLTFSceneExporter.cs:84)
Plattar.Exporter.GenerateGLTF (UnityEngine.GameObject selectedObject) (at Assets/PlattarExporter/Plattar/Editor/Exporter.cs:247)
Plattar.Exporter.GenerateGLTFZipped (UnityEngine.GameObject selectedObject) (at Assets/PlattarExporter/Plattar/Editor/Exporter.cs:210)
Plattar.Exporter.OnGUI () (at Assets/PlattarExporter/Plattar/Editor/Exporter.cs:131)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:367)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:361)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:337)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:398)
UnityEditor.DockArea.OldOnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:388)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:293)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:508)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:491)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:484)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:477)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:449)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/Events/EventHandler.cs:77)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/Events/MouseCaptureDispatchingStrategy.cs:92)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:310)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:275)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at /Users/builduser/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:238)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at /Users/builduser/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:203)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at /Users/builduser/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:44)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:301)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:159)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/Panel.cs:256)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/UIElementsUtility.bindings.cs:404)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/UIElementsUtility.bindings.cs:194)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:187)
`

**Comment by tomahim** [comment]
Hi,

Just came across the same issue, for me what does the trick was that the object I tried to export didn't have vertices but had MeshFilter and MeshRenderer components setup on it. So I just removed these components from this object and then the export succeed.

What help me figure it out was to set a `Debug.Log(gameObject.name)` just before `UnityGLTF.GLTFSceneExporter.ExportPrimitive (UnityEngine.GameObject gameObject)` get called. So then you can identify the object(s) with a vertices issue.

Hope this help
